Repository mitrefireline/simfire, pull requests merged in 2024-07, with the labels that each got.

#24 implement historical fire data layer (BurnMD)
  README.md
  configs/historical_config.yml
  poetry.lock
  pyproject.toml
  simfire/enums.py
  simfire/game/game.py
  simfire/game/managers/fire.py
  simfire/game/sprites.py
  simfire/sim/simulation.py
  simfire/utils/config.py
  simfire/utils/generate_cfd_wind_layer.py
  simfire/utils/layers.py
  simfire/utils/units.py
  simfire/world/rothermel.py
  tests/historical_test.py
Labels: enhancement, operational, size:XL, lgtm, historical

#30 Upgrade version to 2.0.0
  CITATION.cff
  pyproject.toml
Labels: size:XS

#34 Add geopy and fix tests
  .github/workflows/testing.yml
  CITATION.cff
  poetry.lock
  pyproject.toml
  simfire/game/_tests/test_sprites.py
  simfire/world/_tests/test_rothermel.py
Labels: size:M, lgtm, version:patch
